---
- name: Keep edge devices healty
  hosts: localhost

  sources:
  - ansible.eda.webhook:
      host: 0.0.0.0
      port: 8082

  rules:
  - name: Recover the device
    condition: event.payload.message == "error"
    action:
      run_playbook:
        name: eda_playbook_recover.yaml

  - name: Rescan the device
    condition: event.payload.message == "unknown"
    action:
      run_playbook:
        name: eda_playbook_rescan.yaml
