---
- name: Listen for webhook 8888 and Debug
  hosts: all
  sources:
  - ansible.eda.webhook:
      host: 0.0.0.0
      port: 8888
  rules:
  - name: Print all event and vars
    condition: event.payload.Host == 'demo-agent1' and event.payload.Problem == 'monitoring2_trigger2' and event.payload.event_severity == 'High'
    action:
      debug:
        msg:
          - "{{ event.payload }}"
