---
- name: Listen for webhook 8888 and Debug
  hosts: all
  sources:
  - ansible.eda.webhook:
      host: 0.0.0.0
      port: 8888
  rules:
  - name: Print all event and vars
    condition: event.payload.host_host == 'demo-agent1' and event.payload.trigger_name == 'monitoring1_trigger1' and event.payload.event_severity == 'High'
    action:
      debug:
        msg:
          - "{{ event.payload.host_host }}"
          - "{{ event.payload.trigger_name }}"
          - "{{ event.payload.event_severity }}"
