---
- name: Listen for webhook 8888 and Debug
  hosts: all
  sources:
  - ansible.eda.webhook:
      host: 0.0.0.0
      port: 8888
  rules:
  - name: Print all event and vars
    condition: >-
      event.payload.host_host == 'demo-agent1'
      and event.payload.trigger_name == 'monitoring1_trigger1'
      and event.payload.event_severity == 'High'
    action:
      run_job_template:
        name: senario1_action
        organization: Default
        job_args:
          extra_vars:
            z_host_name: "{{ event.payload.host_host }}"
            z_host_id: "{{ event.payload.host_id }}"
            z_event_id: "{{ event.payload.event_id }}"
            z_event_severity: "{{ event.payload.event_severity }}"
            z_trigger_name: "{{ event.payload.trigger_name }}"
