---
- name: Listen for storage-monitor events
  hosts: all
  sources:
  - ansible.eda.webhook:
      host: 0.0.0.0
      port: 8888
  rules:
  - name: Handle Red Hat Insights event
    condition: event.payload is defined
    action:
      debug:
        msg: "Received: {{ event.payload }}"
